WORDS = [
    {"word": "cassette", "hint": "Formato clásico que sobrevivió a fiestas, autos y walkmans."},
    {"word": "neón", "hint": "Brillo de vidriera nocturna bien ochentosa."},
    {"word": "arcade", "hint": "Lugar ideal para perder fichas y dignidad con estilo."},
    {"word": "vinilo", "hint": "Gira, suena y vuelve loco al coleccionista."},
    {"word": "patines", "hint": "Accesorio obligatorio para deslizarse con glamour noventoso."},
    {"word": "boombox", "hint": "Equipo portátil grande, ruidoso y con actitud."},
    {"word": "pixel", "hint": "La unidad mínima del encanto retro digital."},
    {"word": "cometa", "hint": "Se eleva con viento, infancia y cero facturas por estrés."},
    {"word": "robot", "hint": "A veces metálico, a veces torpe, siempre icónico."},
    {"word": "sintetizador", "hint": "Responsable de muchos sonidos gloriosos de los 80."},
    {"word": "galaxia", "hint": "Tema perfecto para portada con aerosoles y luces."},
    {"word": "videoclub", "hint": "Santuario de carátulas, alquileres y multas absurdas."},

    {"word": "año", "hint": "Periodo que pasa más rápido cuando sos adulto."},
    {"word": "niñez", "hint": "Etapa donde todo era más simple (y más barato)."},
    {"word": "montaña", "hint": "Gigante natural que te recuerda lo chico que sos."},
    {"word": "cañón", "hint": "Formación natural o arma, según la época."},
    {"word": "muñeco", "hint": "Compañero de juegos o víctima de experimentos infantiles."},
    {"word": "bañera", "hint": "Lugar para relajarse… o pensar demasiado."},
    {"word": "araña", "hint": "Criatura que nunca es bienvenida en casa."},
    {"word": "leña", "hint": "Esencial para el fuego y el asado."},
    {"word": "daño", "hint": "Consecuencia inevitable de malas decisiones."},
    {"word": "engaño", "hint": "Verdad disfrazada que tarde o temprano se cae."},

    {"word": "teléfono", "hint": "Antes tenía cable, ahora te controla la vida."},
    {"word": "música", "hint": "Idioma universal que no necesita traducción."},
    {"word": "cámara", "hint": "Captura momentos… o los arruina."},
    {"word": "película", "hint": "Excusa perfecta para no salir de casa."},
    {"word": "rádio", "hint": "Medio clásico que nunca murió del todo."},
    {"word": "eléctrico", "hint": "Todo lo moderno depende de esto."},
    {"word": "rápido", "hint": "Velocidad que rara vez es suficiente."},
    {"word": "lógico", "hint": "Lo que debería ser… pero casi nunca es."},
    {"word": "mágico", "hint": "Cuando algo no tiene explicación simple."},
    {"word": "técnico", "hint": "El que arregla lo que rompiste."},

    {"word": "héroe", "hint": "El que aparece cuando todo se complica."},
    {"word": "villano", "hint": "El que cree que tiene razón."},
    {"word": "acción", "hint": "Género donde nadie piensa demasiado."},
    {"word": "drama", "hint": "Donde todos sufren, incluso el espectador."},
    {"word": "comedia", "hint": "Si no te reís, algo falló."},

    {"word": "energía", "hint": "Lo que te falta los lunes."},
    {"word": "física", "hint": "Materia que te hace cuestionar la realidad."},
    {"word": "química", "hint": "Explosiones… a veces controladas."},
    {"word": "biología", "hint": "Todo lo vivo entra acá."},
    {"word": "átomo", "hint": "Más chico que tus problemas… pero importante."},

    {"word": "fútbol", "hint": "Religión no oficial de medio planeta."},
    {"word": "tenis", "hint": "Deporte elegante… hasta que perdés."},
    {"word": "ciclismo", "hint": "Sufrir pero con estilo."},
    {"word": "natación", "hint": "Moverse sin tocar el suelo."},
    {"word": "boxeo", "hint": "Resolver conflictos de forma directa."},

    {"word": "programación", "hint": "Arte de hablarle a una máquina."},
    {"word": "algoritmo", "hint": "Serie de pasos para resolver algo."},
    {"word": "variable", "hint": "Donde guardás tus problemas."},
    {"word": "función", "hint": "Hace cosas… si está bien hecha."},
    {"word": "error", "hint": "Nunca es tu culpa… hasta que sí."},

    {"word": "memoria", "hint": "Donde todo se guarda… o se pierde."},
    {"word": "sistema", "hint": "Funciona… hasta que deja de hacerlo."},
    {"word": "usuario", "hint": "Siempre encuentra cómo romper todo."},
    {"word": "servidor", "hint": "Trabaja para todos, descansa nunca."},
    {"word": "redes", "hint": "Conectan… y distraen."},

    {"word": "ciudad", "hint": "Donde todo pasa, pero nadie descansa."},
    {"word": "pueblo", "hint": "Donde todos se conocen demasiado."},
    {"word": "bosque", "hint": "Lugar perfecto para perderse."},
    {"word": "desierto", "hint": "Nada… y aún así algo."},
    {"word": "océano", "hint": "Inmenso, profundo y desconocido."},

    {"word": "viaje", "hint": "La mejor inversión emocional."},
    {"word": "destino", "hint": "A veces lo elegís, a veces no."},
    {"word": "camino", "hint": "Importa más que el final."},
    {"word": "ruta", "hint": "Larga, recta y llena de decisiones."},
    {"word": "mapa", "hint": "Te guía… si sabés usarlo."},

    {"word": "tiempo", "hint": "Nunca alcanza."},
    {"word": "reloj", "hint": "Recordatorio constante de eso."},
    {"word": "instante", "hint": "Dura poco, vale mucho."},
    {"word": "momento", "hint": "Puede cambiar todo."},
    {"word": "historia", "hint": "Siempre depende de quién la cuenta."},

    {"word": "realidad", "hint": "A veces decepciona."},
    {"word": "sueño", "hint": "Escapatoria mental."},
    {"word": "idea", "hint": "Empieza todo."},
    {"word": "mente", "hint": "Tu mejor aliada… o tu peor enemiga."},
    {"word": "lógica", "hint": "No siempre gana."},

    {"word": "corazón", "hint": "Late… y complica."},
    {"word": "emoción", "hint": "No se puede programar."},
    {"word": "pasión", "hint": "Motor interno."},
    {"word": "miedo", "hint": "Frena más que cualquier obstáculo."},
    {"word": "valor", "hint": "Hacerlo igual."},

    {"word": "creación", "hint": "Traer algo nuevo al mundo."},
    {"word": "diseño", "hint": "Cómo se ve y cómo funciona."},
    {"word": "arte", "hint": "Expresión sin límites."},
    {"word": "estilo", "hint": "Lo que te diferencia."},
    {"word": "forma", "hint": "Importa más de lo que creés."},
]
