WORDS = [
    {"word": "cassette", "hint": "Formato clásico que sobrevivió a fiestas, autos y walkmans."},
    {"word": "neón", "hint": "Brillo de vidriera nocturna bien ochentosa."},
    {"word": "arcade", "hint": "Lugar ideal para perder fichas y dignidad con estilo."},
    {"word": "vinilo", "hint": "Gira, suena y vuelve loco al coleccionista."},
    {"word": "patines", "hint": "Accesorio obligatorio para deslizarse con glamour noventoso."},
    {"word": "boombox", "hint": "Equipo portátil grande, ruidoso y con actitud."},
    {"word": "pixel", "hint": "La unidad mínima del encanto retro digital."},
    {"word": "cometa", "hint": "Se eleva con viento, infancia y cero facturas por estrés."},
    {"word": "robot", "hint": "A veces metálico, a veces torpe, siempre icónico."},
    {"word": "sintetizador", "hint": "Responsable de muchos sonidos gloriosos de los 80."},
    {"word": "galaxia", "hint": "Tema perfecto para portada con aerosoles y luces."},
    {"word": "videoclub", "hint": "Santuario de carátulas, alquileres y multas absurdas."},

    {"word": "año", "hint": "Periodo que pasa más rápido cuando sos adulto."},
    {"word": "niñez", "hint": "Etapa donde todo era más simple (y más barato)."},
    {"word": "montaña", "hint": "Gigante natural que te recuerda lo chico que sos."},
    {"word": "cañón", "hint": "Formación natural o arma, según la época."},
    {"word": "muñeco", "hint": "Compañero de juegos o víctima de experimentos infantiles."},
    {"word": "bañera", "hint": "Lugar para relajarse… o pensar demasiado."},
    {"word": "araña", "hint": "Criatura que nunca es bienvenida en casa."},
    {"word": "leña", "hint": "Esencial para el fuego y el asado."},
    {"word": "daño", "hint": "Consecuencia inevitable de malas decisiones."},
    {"word": "engaño", "hint": "Verdad disfrazada que tarde o temprano se cae."},

    {"word": "teléfono", "hint": "Antes tenía cable, ahora te controla la vida."},
    {"word": "música", "hint": "Idioma universal que no necesita traducción."},
    {"word": "cámara", "hint": "Captura momentos… o los arruina."},
    {"word": "película", "hint": "Excusa perfecta para no salir de casa."},
    {"word": "rádio", "hint": "Medio clásico que nunca murió del todo."},
    {"word": "eléctrico", "hint": "Todo lo moderno depende de esto."},
    {"word": "rápido", "hint": "Velocidad que rara vez es suficiente."},
    {"word": "lógico", "hint": "Lo que debería ser… pero casi nunca es."},
    {"word": "mágico", "hint": "Cuando algo no tiene explicación simple."},
    {"word": "técnico", "hint": "El que arregla lo que rompiste."},

    {"word": "héroe", "hint": "El que aparece cuando todo se complica."},
    {"word": "villano", "hint": "El que cree que tiene razón."},
    {"word": "acción", "hint": "Género donde nadie piensa demasiado."},
    {"word": "drama", "hint": "Donde todos sufren, incluso el espectador."},
    {"word": "comedia", "hint": "Si no te reís, algo falló."},

    {"word": "energía", "hint": "Lo que te falta los lunes."},
    {"word": "física", "hint": "Materia que te hace cuestionar la realidad."},
    {"word": "química", "hint": "Explosiones… a veces controladas."},
    {"word": "biología", "hint": "Todo lo vivo entra acá."},
    {"word": "átomo", "hint": "Más chico que tus problemas… pero importante."},

    {"word": "fútbol", "hint": "Religión no oficial de medio planeta."},
    {"word": "tenis", "hint": "Deporte elegante… hasta que perdés."},
    {"word": "ciclismo", "hint": "Sufrir pero con estilo."},
    {"word": "natación", "hint": "Moverse sin tocar el suelo."},
    {"word": "boxeo", "hint": "Resolver conflictos de forma directa."},

    {"word": "programación", "hint": "Arte de hablarle a una máquina."},
    {"word": "algoritmo", "hint": "Serie de pasos para resolver algo."},
    {"word": "variable", "hint": "Donde guardás tus problemas."},
    {"word": "función", "hint": "Hace cosas… si está bien hecha."},
    {"word": "error", "hint": "Nunca es tu culpa… hasta que sí."},

    {"word": "memoria", "hint": "Donde todo se guarda… o se pierde."},
    {"word": "sistema", "hint": "Funciona… hasta que deja de hacerlo."},
    {"word": "usuario", "hint": "Siempre encuentra cómo romper todo."},
    {"word": "servidor", "hint": "Trabaja para todos, descansa nunca."},
    {"word": "redes", "hint": "Conectan… y distraen."},

    {"word": "ciudad", "hint": "Donde todo pasa, pero nadie descansa."},
    {"word": "pueblo", "hint": "Donde todos se conocen demasiado."},
    {"word": "bosque", "hint": "Lugar perfecto para perderse."},
    {"word": "desierto", "hint": "Nada… y aún así algo."},
    {"word": "océano", "hint": "Inmenso, profundo y desconocido."},

    {"word": "viaje", "hint": "La mejor inversión emocional."},
    {"word": "destino", "hint": "A veces lo elegís, a veces no."},
    {"word": "camino", "hint": "Importa más que el final."},
    {"word": "ruta", "hint": "Larga, recta y llena de decisiones."},
    {"word": "mapa", "hint": "Te guía… si sabés usarlo."},

    {"word": "tiempo", "hint": "Nunca alcanza."},
    {"word": "reloj", "hint": "Recordatorio constante de eso."},
    {"word": "instante", "hint": "Dura poco, vale mucho."},
    {"word": "momento", "hint": "Puede cambiar todo."},
    {"word": "historia", "hint": "Siempre depende de quién la cuenta."},

    {"word": "realidad", "hint": "A veces decepciona."},
    {"word": "sueño", "hint": "Escapatoria mental."},
    {"word": "idea", "hint": "Empieza todo."},
    {"word": "mente", "hint": "Tu mejor aliada… o tu peor enemiga."},
    {"word": "lógica", "hint": "No siempre gana."},

    {"word": "corazón", "hint": "Late… y complica."},
    {"word": "emoción", "hint": "No se puede programar."},
    {"word": "pasión", "hint": "Motor interno."},
    {"word": "miedo", "hint": "Frena más que cualquier obstáculo."},
    {"word": "valor", "hint": "Hacerlo igual."},

    {"word": "creación", "hint": "Traer algo nuevo al mundo."},
    {"word": "diseño", "hint": "Cómo se ve y cómo funciona."},
    {"word": "arte", "hint": "Expresión sin límites."},
    {"word": "estilo", "hint": "Lo que te diferencia."},
    {"word": "forma", "hint": "Importa más de lo que creés."},
]

EXTRA_WORDS = [
    {"word": "brújula", "hint": "Te orienta cuando tu sentido de ubicación se fue de vacaciones."},
    {"word": "biblioteca", "hint": "Templo silencioso de historias, polvo y sabiduría prestada."},
    {"word": "astronauta", "hint": "Profesional de mirar la Tierra desde una ventana imposible."},
    {"word": "murciélago", "hint": "Vuela de noche y no necesita capa para impresionar."},
    {"word": "laberinto", "hint": "Camino diseñado para que dudes de cada decisión."},
    {"word": "jirafa", "hint": "Animal que ve venir los problemas antes que todos."},
    {"word": "tiburón", "hint": "Sonrisa intimidante con aleta incluida."},
    {"word": "pingüino", "hint": "Elegante, torpe y perfectamente vestido para el frío."},
    {"word": "volcán", "hint": "Montaña con muy mal carácter interior."},
    {"word": "catarata", "hint": "Agua que decidió bajar con todo el dramatismo posible."},
    {"word": "tormenta", "hint": "El cielo haciendo ruido porque puede."},
    {"word": "relámpago", "hint": "Flash natural que llega antes que el trueno."},
    {"word": "navegante", "hint": "Persona que entiende mapas, vientos y terquedades del mar."},
    {"word": "pirámide", "hint": "Monumento antiguo con geometría y misterio de sobra."},
    {"word": "esfinge", "hint": "Guardián de piedra con cara de acertijo eterno."},
    {"word": "dinosaurio", "hint": "Gigante prehistórico que todavía vende entradas al museo."},
    {"word": "fósil", "hint": "Recuerdo muy viejo que la tierra guardó con paciencia."},
    {"word": "planeta", "hint": "Vecindario redondo dando vueltas por el espacio."},
    {"word": "satélite", "hint": "Compañero orbital que no se pierde de vista."},
    {"word": "meteorito", "hint": "Piedra espacial con entrada explosiva."},
    {"word": "constelación", "hint": "Dibujo imaginario hecho con estrellas reales."},
    {"word": "telescopio", "hint": "Acerca lo lejano sin moverte del lugar."},
    {"word": "microscopio", "hint": "Revela mundos que tus ojos ignoran."},
    {"word": "laboratorio", "hint": "Lugar donde la curiosidad usa guardapolvo."},
    {"word": "experimento", "hint": "Pregunta hecha con frascos, cables o paciencia."},
    {"word": "hipótesis", "hint": "Suposición elegante antes de comprobar si era cualquiera."},
    {"word": "ecuación", "hint": "Frase matemática con incógnitas que se hacen las misteriosas."},
    {"word": "geometría", "hint": "El arte de discutir con líneas y ángulos."},
    {"word": "diccionario", "hint": "Casa ordenada de las palabras."},
    {"word": "caligrafía", "hint": "Escribir bonito, incluso cuando el pulso no colabora."},
    {"word": "máquina", "hint": "Hace trabajo, ruido y a veces berrinches."},
    {"word": "engranaje", "hint": "Diente mecánico que trabaja en equipo."},
    {"word": "bicicleta", "hint": "Dos ruedas, equilibrio y libertad sin combustible."},
    {"word": "helicóptero", "hint": "Aparato que vence al aire a fuerza de girar."},
    {"word": "submarino", "hint": "Vehículo que prefiere viajar por abajo del problema."},
    {"word": "locomotora", "hint": "Gigante ferroviario con nostalgia de vapor."},
    {"word": "semáforo", "hint": "Árbitro urbano de colores autoritarios."},
    {"word": "rascacielos", "hint": "Edificio que quiso saludar a las nubes."},
    {"word": "ascensor", "hint": "Cuarto pequeño que sube y baja conversaciones incómodas."},
    {"word": "paraguas", "hint": "Techo portátil contra nubes malintencionadas."},
    {"word": "almohada", "hint": "Cómplice blanda de sueños y siestas heroicas."},
    {"word": "chocolate", "hint": "Solución dulce para problemas no necesariamente reales."},
    {"word": "heladera", "hint": "Guardián frío de sobras y esperanzas nocturnas."},
    {"word": "cacerola", "hint": "Recipiente de cocina y percusión de emergencia."},
    {"word": "zanahoria", "hint": "Raíz naranja con fama de mejorar la vista."},
    {"word": "sandía", "hint": "Fruta de verano con demasiadas semillas invitadas."},
    {"word": "alfajor", "hint": "Dulce redondo que siempre parece buena idea."},
    {"word": "empanada", "hint": "Paquete comestible con debate de repulgue incluido."},
    {"word": "guitarra", "hint": "Seis cuerdas para conquistar fogones y vecinos pacientes."},
    {"word": "batería", "hint": "Instrumento para descargar energía con autorización musical."},
    {"word": "trompeta", "hint": "Metal brillante que no sabe hablar bajito."},
    {"word": "orquesta", "hint": "Multitud organizada haciendo magia sonora."},
    {"word": "melodía", "hint": "Línea musical que se queda a vivir en tu cabeza."},
    {"word": "teatro", "hint": "Lugar donde mentir bien se llama actuar."},
    {"word": "máscara", "hint": "Cara prestada para ocultar o exagerar emociones."},
    {"word": "escultura", "hint": "Arte que ocupa espacio con intención."},
    {"word": "acuarela", "hint": "Pintura que viaja sobre agua y papel."},
    {"word": "caricatura", "hint": "Retrato exagerado con permiso para burlarse."},
    {"word": "aventura", "hint": "Plan que suena divertido hasta que falta señal."},
    {"word": "misterio", "hint": "Problema con sombrero, sombra y música de suspenso."},
    {"word": "fantasía", "hint": "Realidad con dragones y mejores reglas."},
    {"word": "hechicero", "hint": "Alguien que resuelve con magia lo que otros complican."},
    {"word": "dragón", "hint": "Lagarto legendario con calefacción incorporada."},
    {"word": "castillo", "hint": "Casa grande, antigua y difícil de limpiar."},
    {"word": "tesoro", "hint": "Algo valioso que siempre exige mapa o paciencia."},
    {"word": "esmeralda", "hint": "Piedra verde con nombre de lujo."},
    {"word": "zafiro", "hint": "Gema azul que parece guardar un pedazo de cielo."},
    {"word": "diamante", "hint": "Brillo duro, caro y dramático."},
    {"word": "camaleón", "hint": "Experto en pasar desapercibido cambiando de look."},
    {"word": "mariposa", "hint": "Antes fue oruga; gran ejemplo de cambio de estilo."},
    {"word": "hormiga", "hint": "Pequeña trabajadora con fuerza desproporcionada."},
    {"word": "caracol", "hint": "Viajero lento con casa propia."},
    {"word": "delfín", "hint": "Mamífero marino con sonrisa de inteligencia sospechosa."},
    {"word": "ballena", "hint": "Gigante del océano con canciones profundas."},
    {"word": "canguro", "hint": "Saltador profesional con bolsillo familiar."},
    {"word": "koala", "hint": "Especialista en dormir abrazado a un árbol."},
    {"word": "búho", "hint": "Ave nocturna con cara de saberlo todo."},
    {"word": "águila", "hint": "Mira desde arriba y no se le escapa casi nada."},
    {"word": "libélula", "hint": "Insecto liviano con alas de vitral."},
    {"word": "mandarina", "hint": "Cítrico práctico que perfuma dedos sin pedir permiso."},
    {"word": "jengibre", "hint": "Raíz picante con actitud medicinal."},
    {"word": "canela", "hint": "Aroma dulce que convierte todo en merienda."},
    {"word": "vainilla", "hint": "Sabor clásico que nunca se rinde."},
    {"word": "aventurero", "hint": "Persona que escucha 'peligro' y entiende 'plan'."},
    {"word": "arquitecto", "hint": "Dibuja lugares antes de que existan."},
    {"word": "bombero", "hint": "Corre hacia el fuego cuando todos corren al revés."},
    {"word": "carpintero", "hint": "Convierte madera en cosas útiles y olorosas."},
    {"word": "jardinero", "hint": "Negocia diariamente con plantas, tierra y clima."},
    {"word": "periodista", "hint": "Pregunta incómoda con libreta o micrófono."},
    {"word": "astronomía", "hint": "Ciencia de mirar arriba con preguntas enormes."},
    {"word": "arqueología", "hint": "Investigar el pasado con pincel y paciencia."},
    {"word": "fotografía", "hint": "Atrapar luz antes de que el momento se escape."},
    {"word": "electricidad", "hint": "Energía invisible que se nota cuando falta."},
    {"word": "imaginación", "hint": "Fábrica mental sin horario de cierre."},
    {"word": "curiosidad", "hint": "Motor que abre puertas y pestañas del navegador."},
    {"word": "paciencia", "hint": "Superpoder necesario para filas, bugs y plantas."},
    {"word": "estrategia", "hint": "Pensar antes para sufrir menos después."},
    {"word": "victoria", "hint": "Final feliz que suele exigir varios intentos."},
]

WORDS.extend(EXTRA_WORDS)
